\encoding UTF8
SET client_encoding = 'UTF8';

INSERT INTO news_posts (kind, title, excerpt, body, source)
VALUES
('idiom','A piece of cake','проще простого','The test was a piece of cake.','Idiom Bank'),
('idiom','Break the ice','разрядить обстановку','He told a joke to break the ice.','Idiom Bank'),
('idiom','A blessing in disguise','нет худа без добра','Losing that job was a blessing in disguise.','Idiom Bank'),
('idiom','Once in a blue moon','крайне редко','We go out together once in a blue moon.','Idiom Bank'),
('idiom','Under the weather','плохо себя чувствовать','I''m feeling under the weather today.','Idiom Bank'),
('idiom','Hit the nail on the head','попасть в точку','You hit the nail on the head with that comment.','Idiom Bank'),
('idiom','Let the cat out of the bag','выболтать секрет','He let the cat out of the bag about the surprise.','Idiom Bank'),
('idiom','Cost an arm and a leg','стоить целое состояние','That laptop cost an arm and a leg.','Idiom Bank'),
('idiom','Spill the beans','раскрыть тайну','Come on—spill the beans!','Idiom Bank'),
('idiom','The ball is in your court','теперь твоя очередь','I''ve explained everything—the ball is in your court.','Idiom Bank'),
('idiom','Call it a day','закругляться','We''ve done enough—let''s call it a day.','Idiom Bank'),
('idiom','Cut corners','делать кое-как','Don''t cut corners on safety.','Idiom Bank'),
('idiom','Bite the bullet','собраться с духом','I finally bit the bullet and called the doctor.','Idiom Bank'),
('idiom','Beat around the bush','ходить вокруг да около','Stop beating around the bush and say it.','Idiom Bank'),
('idiom','Back to the drawing board','начать заново','The plan failed—back to the drawing board.','Idiom Bank'),
('idiom','Burn the midnight oil','работать допоздна','She burned the midnight oil to finish the project.','Idiom Bank'),
('idiom','By the book','по правилам','Our accountant does everything by the book.','Idiom Bank'),
('idiom','Cry over spilled milk','плакать по ушедшему','Don''t cry over spilled milk—move on.','Idiom Bank'),
('idiom','Get cold feet','струсить','He got cold feet before the speech.','Idiom Bank'),
('idiom','Get the hang of it','разобраться','You''ll get the hang of it after a few tries.','Idiom Bank'),
('idiom','Go the extra mile','сделать сверх нормы','She always goes the extra mile for customers.','Idiom Bank'),
('idiom','Hang in there','держись','Hang in there—things will improve.','Idiom Bank'),
('idiom','In hot water','в неприятностях','He''s in hot water with his boss.','Idiom Bank'),
('idiom','It takes two to tango','виноваты оба','Stop blaming her—it takes two to tango.','Idiom Bank'),
('idiom','Jump on the bandwagon','присоединиться к тренду','Everyone jumped on the bandwagon after it became popular.','Idiom Bank'),
('idiom','Keep an eye on','присмотреть','Can you keep an eye on my bag?','Idiom Bank'),
('idiom','Keep your chin up','не унывай','Keep your chin up—you can do it.','Idiom Bank'),
('idiom','Kill two birds with one stone','убить двух зайцев','I''ll shop on the way home—kill two birds with one stone.','Idiom Bank'),
('idiom','Leave no stone unturned','перепробовать всё','We''ll leave no stone unturned to find the answer.','Idiom Bank'),
('idiom','Make ends meet','сводить концы с концами','It''s hard to make ends meet these days.','Idiom Bank'),
('idiom','Miss the boat','упустить шанс','If you don''t apply now, you''ll miss the boat.','Idiom Bank'),
('idiom','On the same page','понимать одинаково','Let''s confirm we''re on the same page.','Idiom Bank'),
('idiom','Pull someone''s leg','подшучивать','Relax—I''m just pulling your leg.','Idiom Bank'),
('idiom','Put all your eggs in one basket','рисковать всем','Don''t put all your eggs in one basket.','Idiom Bank'),
('idiom','Read between the lines','читать между строк','Read between the lines—he''s unhappy.','Idiom Bank'),
('idiom','Rule of thumb','общее правило','As a rule of thumb, save 10%.','Idiom Bank'),
('idiom','See eye to eye','сходиться во мнениях','We don''t always see eye to eye.','Idiom Bank'),
('idiom','Speak of the devil','лёгок на помине','Speak of the devil—here he comes!','Idiom Bank'),
('idiom','Take it with a grain of salt','воспринимать скептически','Take his promises with a grain of salt.','Idiom Bank'),
('idiom','The best of both worlds','лучшее из двух миров','Remote work gives me the best of both worlds.','Idiom Bank'),
('idiom','Throw in the towel','сдаться','Don''t throw in the towel yet.','Idiom Bank'),
('idiom','Time flies','время летит','Time flies when you''re busy.','Idiom Bank'),
('idiom','Up in the air','неясно','Our plans are still up in the air.','Idiom Bank'),
('idiom','When pigs fly','никогда','He''ll apologize when pigs fly.','Idiom Bank'),
('idiom','Wrap your head around','осмыслить','I can''t wrap my head around this bug.','Idiom Bank'),
('idiom','A dime a dozen','пруд пруди','Cheap earbuds are a dime a dozen.','Idiom Bank'),
('idiom','Add fuel to the fire','подлить масла в огонь','Don''t add fuel to the fire with that comment.','Idiom Bank'),
('idiom','At the drop of a hat','в любой момент','She''d travel at the drop of a hat.','Idiom Bank'),
('idiom','Bark up the wrong tree','ошибаться адресом','You''re barking up the wrong tree blaming me.','Idiom Bank'),
('idiom','Bite off more than you can chew','взять на себя слишком много','I bit off more than I can chew.','Idiom Bank'),
('idiom','Blow off steam','выпустить пар','Go for a run to blow off steam.','Idiom Bank'),
('idiom','Break a leg','ни пуха ни пера','Break a leg on your performance!','Idiom Bank'),
('idiom','Bring home the bacon','зарабатывать деньги','She brings home the bacon for the family.','Idiom Bank'),
('idiom','Caught red-handed','поймать с поличным','He was caught red-handed cheating.','Idiom Bank'),
('idiom','Close but no cigar','почти, но нет','Nice try—close but no cigar.','Idiom Bank'),
('idiom','Come rain or shine','при любых обстоятельствах','I jog come rain or shine.','Idiom Bank'),
('idiom','Cut to the chase','к делу','Cut to the chase—what do you want?','Idiom Bank'),
('idiom','Don''t judge a book by its cover','не суди по внешности','Don''t judge a book by its cover.','Idiom Bank'),
('idiom','Down to earth','простой, приземлённый','Despite fame, she''s down to earth.','Idiom Bank'),
('idiom','Face the music','ответить за поступки','He had to face the music.','Idiom Bank'),
('idiom','Get out of hand','выйти из-под контроля','The meeting got out of hand.','Idiom Bank'),
('idiom','Get something off your chest','выговориться','I need to get this off my chest.','Idiom Bank'),
('idiom','Give someone the cold shoulder','игнорировать','She gave him the cold shoulder.','Idiom Bank'),
('idiom','Go down in flames','провалиться','The plan went down in flames.','Idiom Bank'),
('idiom','Go with the flow','плыть по течению','Just go with the flow.','Idiom Bank'),
('idiom','Hit the sack','лечь спать','I''m tired—I''m going to hit the sack.','Idiom Bank'),
('idiom','In the nick of time','в последний момент','They arrived in the nick of time.','Idiom Bank'),
('idiom','Keep something under your hat','держать в секрете','Keep it under your hat for now.','Idiom Bank'),
('idiom','Kick the bucket','сыграть в ящик','He joked he''d travel before he kicks the bucket.','Idiom Bank'),
('idiom','Know the ropes','знать как всё устроено','She knows the ropes in this office.','Idiom Bank'),
('idiom','Let sleeping dogs lie','не буди лихо','Let sleeping dogs lie.','Idiom Bank'),
('idiom','Make a long story short','короче говоря','To make a long story short, we won.','Idiom Bank'),
('idiom','On thin ice','на тонком льду','You''re on thin ice with the teacher.','Idiom Bank'),
('idiom','Out of the blue','внезапно','Out of the blue, he called me.','Idiom Bank'),
('idiom','Over the moon','на седьмом небе','She was over the moon about the news.','Idiom Bank'),
('idiom','Play it by ear','импровизировать','We don''t have a plan—let''s play it by ear.','Idiom Bank'),
('idiom','Put your foot in your mouth','ляпнуть','I really put my foot in my mouth.','Idiom Bank'),
('idiom','Sit on the fence','колебаться','Stop sitting on the fence—choose.','Idiom Bank'),
('idiom','Speak your mind','говорить прямо','Feel free to speak your mind.','Idiom Bank'),
('idiom','Take the bull by the horns','взять быка за рога','She took the bull by the horns and fixed it.','Idiom Bank'),
('idiom','The last straw','последняя капля','That was the last straw for me.','Idiom Bank'),
('idiom','Through thick and thin','в горе и радости','They stayed together through thick and thin.','Idiom Bank'),
('idiom','Throw someone under the bus','подставить','He threw his teammate under the bus.','Idiom Bank'),
('idiom','Turn a blind eye','закрыть глаза','They turned a blind eye to the problem.','Idiom Bank'),
('idiom','Under your nose','прямо под носом','The answer was under your nose.','Idiom Bank'),
('idiom','Wear many hats','совмещать роли','In a startup you wear many hats.','Idiom Bank'),
('idiom','A taste of your own medicine','твоими же методами','He got a taste of his own medicine.','Idiom Bank'),
('idiom','Bite your tongue','прикусить язык','I had to bite my tongue.','Idiom Bank'),
('idiom','Break the bank','разориться','Buying that car would break the bank.','Idiom Bank'),
('idiom','Call the shots','командовать','She calls the shots here.','Idiom Bank'),
('idiom','Cut somebody some slack','дать поблажку','Cut him some slack—he''s new.','Idiom Bank'),
('idiom','Get the ball rolling','дать старт','Let''s get the ball rolling.','Idiom Bank'),
('idiom','Give it a shot','попробовать','Give it a shot—you might like it.','Idiom Bank'),
('idiom','In the long run','в долгосрочной перспективе','In the long run, it will pay off.','Idiom Bank'),
('idiom','Keep your fingers crossed','держать кулачки','Keep your fingers crossed for me.','Idiom Bank'),
('idiom','Make up your mind','решиться','Make up your mind already.','Idiom Bank'),
('idiom','No pain, no gain','без труда не вытащишь','No pain, no gain.','Idiom Bank'),
('idiom','On cloud nine','на седьмом небе','He''s on cloud nine after the win.','Idiom Bank'),
('idiom','Out of sight, out of mind','с глаз долой — из сердца вон','Out of sight, out of mind.','Idiom Bank'),
('idiom','Pull yourself together','возьми себя в руки','Pull yourself together and focus.','Idiom Bank'),
('idiom','The tip of the iceberg','вершина айсберга','This bug is just the tip of the iceberg.','Idiom Bank');